card:

  revision: ${revision}

spring:

  web:
    resources:
      static-locations: classpath:/static/

  cloud:
    gcp:
      project-id: ec2u-card
      datastore:
        namespace: next # !!! use GAE version id

server:

  # see https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.webserver.use-behind-a-proxy-server

  forward-headers-strategy: NATIVE

  error:
    whitelabel:
      enabled: false