spring:

  security:
    saml2:
      relyingparty:
        registration:

          local:
            identityprovider:
              entity-id: https://accounts.google.com/o/saml2?idpid=C010aus0d
              verification.credentials:
                - certificate-location: "classpath:saml/local.crt"
              singlesignon.url: https://accounts.google.com/o/saml2/idp?idpid=C010aus0d
              singlesignon.sign-request: false
