runtime: java11
instance_class: F2

handlers:

  - url: /(.*\.(html|css|js|svg|png|webp))$
    static_files: static/\1
    upload: static/.*$
    secure: always

  - url: .*
    script: auto
    secure: always