
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule dir_module modules/mod_dir.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule mime_module modules/mod_mime.so
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule unixd_module modules/mod_unixd.so

ServerRoot "/usr/local/apache2"
ServerAdmin cc@ml.ec2u.eu
ServerName localhost
Listen 8080

DocumentRoot "/usr/local/apache2/htdocs"
DirectoryIndex index.html
ErrorDocument 404 /index.html

ErrorLog /proc/self/fd/2
LogLevel warn

# the following configuration enables Apache to consider as PHP script all those files without any extension

#		RewriteEngine On
#		RewriteCond "%{REQUEST_FILENAME}" !-d
#		RewriteRule "!\." "-" [H=application/x-httpd-php]


<Directory />
    AllowOverride none
    Require all denied
</Directory>

<Directory "/usr/local/apache2/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

<Files ".ht*">
    Require all denied
</Files>

#<Location /profile>
#	AuthType shibboleth
#	Require shibboleth
#</Location>


<IfModule unixd_module>
	User www-data
	Group www-data
</IfModule>

<IfModule log_config_module>

    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common

    CustomLog /proc/self/fd/1 common

</IfModule>

<IfModule mime_module>

    TypesConfig conf/mime.types

    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz

</IfModule>


