name: deploy-next

on:

  push:

    branches: [ next ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - id: package
        run: mvn --file pom.xml --batch-mode package

  deploy:

    needs: build
    runs-on: ubuntu-latest

    permissions:

      contents: read
      id-token: write

    steps:

      - uses: actions/checkout@v2

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          deliverables: pom.xml
          version: next
          promote: false