name: Mirror development release branch to next

on:

  push:

    branches: [ 'release/0.0' ]

env:

  source: ${{ github.ref_name }}
  target: next


jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

      - name: Mirror the source branch to target
        uses: google/mirror-branch-action@v1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source: ${{ env.source }}
          dest: ${{ env.target }}
